name: Trigger auto deployment for azb53fastapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ azb52containerapp ]
    paths:
    - '**'
    - '.github/workflows/azb53fastapi-AutoDeployTrigger-4a954252-d087-4c3a-90fe-31f073b905b9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZB53FASTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZB53FASTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZB53FASTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: azb53acr.azurecr.io
          registryUsername: ${{ secrets.AZB53FASTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZB53FASTAPI_REGISTRY_PASSWORD }}
          containerAppName: azb53fastapi
          resourceGroup: azb53conapp
          imageToBuild: azb53acr.azurecr.io/azb53fastapi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


