name: Trigger auto deployment for azb55github

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ azb55containerapp ]
    paths:
    - '**'
    - '.github/workflows/azb55github-AutoDeployTrigger-0bbc94f1-61d8-4f33-83fb-3a9b8b104bab.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZB55GITHUB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZB55GITHUB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZB55GITHUB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: azb55acr.azurecr.io
          registryUsername: ${{ secrets.AZB55GITHUB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZB55GITHUB_REGISTRY_PASSWORD }}
          containerAppName: azb55github
          resourceGroup: azb55containerapp
          imageToBuild: azb55acr.azurecr.io/azb55fastapi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


